version: "3.0"
services:
  elastic_db:
    build:
      context: .
      dockerfile: docker/db.Dockerfile
    ports:
      - "3306:3306"
  elastic_web:
    build:
      context: .
      dockerfile: docker/web.Dockerfile
    links:
      - elastic_db
      - elastic_php_fpm
    volumes:
      - .:/var/log/nginx
      - .:/etc/nginx/sites-available
    ports:
      - "8080:80"
  elastic_php_fpm:
    build:
      context: .
      dockerfile: docker/php.Dockerfile
    links:
      - elastic_db
    volumes:
      - .:/home/elastic
  elastic_app:
    build:
      context: .
      dockerfile: docker/app.Dockerfile
    links:
      - elastic_db
      - elastic_web
      - elastic_php_fpm
    volumes:
      - .:/home/elastic
