version: "3.0"
services:
  elastic_db:
    build:
      context: .
      dockerfile: docker/db.Dockerfile
    ports:
      - "3306:3306"
  elastic_app:
    build:
      context: .
      dockerfile: docker/app.Dockerfile
    tty: true
    restart: always
    volumes:
      - .:/home/elastic
  elastic_web:
    build:
      context: .
      dockerfile: docker/web.Dockerfile
    depends_on:
      - elastic_app
    links:
      - elastic_php_fpm
      - elastic_db
    restart: always
    volumes:
      - .:/var/log/nginx
      - .:/etc/nginx/sites-available
      - .:/home/elastic
    ports:
      - "80:80"
      - "443:443"
  elastic_php_fpm:
    build:
      context: .
      dockerfile: docker/php.Dockerfile
    depends_on:
      - elastic_app
    links:
      - elastic_db
    expose:
      - "9000"
    volumes:
      - .:/home/elastic
  elastic_beanstalkd:
    build:
      context: .
      dockerfile: docker/beanstalkd.Dockerfile
    ports:
      - "11300:11300"
    privileged: true
    depends_on:
      - elastic_php_fpm
  elastic_php_worker:
    build:
      context: .
      dockerfile: docker/php_worker.Dockerfile
    depends_on:
      - elastic_app
    links:
      - elastic_beanstalkd
      - elastic_db
    volumes:
      - .:/home/elastic
