version: "3.0"
services:
  elastic_db:
    build:
      context: .
      dockerfile: docker/db.Dockerfile
    ports:
      - "3306:3306"
  nginx_1:
    build:
      context: .
      dockerfile: docker/web.Dockerfile
    links:
      - elastic_db
      - php-fpm_1
    volumes:
      - .:/var/log/nginx
      - .:/etc/nginx/sites-available
    ports:
      - "8080:80"
      - "443:443"
  php-fpm_1:
    build:
      context: .
      dockerfile: docker/php.Dockerfile
    volumes:
      - .:/home/elastic
  elastic_app:
    build:
      context: .
      dockerfile: docker/app.Dockerfile
    links:
      - elastic_db
      - nginx_1
      - php-fpm_1
    ports:
      - "80:80"
    volumes:
      - .:/home/elastic
